version: '3'
services:
  users-db:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file:
      - .env
    volumes:
      - ./user-micro/sql:/docker-entrypoint-initdb.d
    networks:
      - security-network
    restart: always


  user-micro:
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - 8081:8080
      depends_on:
        - users-db
      environment:
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
      networks:
        - security-network
      restart: always

networks:
  security-network: